# Render.com deployment configuration
# Deploy at: https://render.com

services:
  - type: web
    name: hiv-analytics-platform
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements_deploy.txt
    startCommand: streamlit run src/visualization/dashboards/main_dashboard.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    healthCheckPath: /_stcore/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_PORT
        value: $PORT

